#spring.application.name=bff-agendador-tarefas
#
#usuario.url=localhost:8080/usuario
#agendador-tarefas.url=localhost:8081/tarefas
#notificacao.url= localhost:8082/email
#
#server.port=8083
#
#cron.horario=0 0/5 * * * ?
#
#usuario.email=desenvolvedor@dev.com
#usuario.senha=123d

spring.application.name=bff-agendador-tarefas

usuario.url=${USUARIO_URL}
agendador-tarefas.url=${AGENDADOR_URL}
notificacao.url=${NOTIFICACAO_URL}

server.port=${SERVER_PORT:8083}

cron.horario=${CRON_HORARIO}

usuario.email=${USUARIO_EMAIL}
usuario.senha=${USUARIO_SENHA}
